"""Add Tier 4 CFD Master Tables

Revision ID: 5546c5dbaa7f
Revises: 
Create Date: 2026-09-18 17:54:06.619045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5546c5dbaa7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tier4_scenario_metadata',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('site_name', sa.String(), nullable=False),
    sa.Column('scenario_type', sa.String(), nullable=False),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('total_sources', sa.Integer(), nullable=True),
    sa.Column('max_hazard_index', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_index(op.f('ix_tier4_scenario_metadata_scenario_id'), 'tier4_scenario_metadata', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_tier4_scenario_metadata_site_name'), 'tier4_scenario_metadata', ['site_name'], unique=False)
    op.create_table('tier4_3d_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['tier4_scenario_metadata.scenario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tier4_3d_assets_scenario_id'), 'tier4_3d_assets', ['scenario_id'], unique=False)
    op.create_table('tier4_receptor_timeseries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('building_id', sa.String(), nullable=True),
    sa.Column('timestep_sec', sa.Integer(), nullable=False),
    sa.Column('pollutant', sa.String(), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['tier4_scenario_metadata.scenario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tier4_receptor_timeseries_building_id'), 'tier4_receptor_timeseries', ['building_id'], unique=False)
    op.create_index(op.f('ix_tier4_receptor_timeseries_scenario_id'), 'tier4_receptor_timeseries', ['scenario_id'], unique=False)
    op.create_table('tier4_surface_impacts_2d',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('pollutant', sa.String(), nullable=False),
    sa.Column('hazard_zone', sa.String(), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['tier4_scenario_metadata.scenario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tier4_surface_impacts_2d_geometry', 'tier4_surface_impacts_2d', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_tier4_surface_impacts_2d_scenario_id'), 'tier4_surface_impacts_2d', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tier4_3d_assets')
    op.drop_table('tier4_receptor_timeseries')
    op.drop_table('tier4_surface_impacts_2d')
    op.drop_table('tier4_scenario_metadata')
    # ### end Alembic commands ###
